export const AdminLogin = () => import(/* webpackChunkName: "home" */ './Login.vue')

export const AdminDashboard = () => import(/* webpackChunkName: "home" */ './Dashboard.vue')
export const Users = () => import(/* webpackChunkName: "users" */ './Users.vue')
export const UserTransactions = () => import(/* webpackChunkName: "userTransactions" */ './UserTransactions.vue')
export const ViewPlans = () => import(/* webpackChunkName: "viewPlans" */ './ViewPlans.vue')
export const ViewDeposits = () => import(/* webpackChunkName: "viewDeposits" */ './ViewDeposits.vue')
export const ViewInvestments = () => import(/* webpackChunkName: "viewInvestments" */ './ViewInvestments.vue')
export const ViewBankWithdrawals = () => import(/* webpackChunkName: "viewBankWithdrawals" */'./ViewBankWithdrawals.vue')
export const ViewWalletWithdrawals = () => import(/* webpackChunkName: "viewWalletWithdrawals" */ './ViewWalletWithdrawals.vue')
export const ViewBillingTypes = () => import(/* webpackChunkName: "viewBillingTypes" */ './ViewBillingTypes.vue')
export const ViewBillingCodes = () => import(/* webpackChunkName: "viewBillingCodes" */'./ViewBillingCodes.vue')
export const ViewMessages = () => import(/* webpackChunkName: "viewMessages" */ './ViewMessages.vue')
export const AccountSettings = () => import(/* webpackChunkName: "viewAccountSettings" */ './AccountSettings.vue')
export const LiveChat = () => import(/* webpackChunkName: "LiveChat" */ './LiveChat.vue')
export const PaymentGateway = () => import(/* webpackChunkName: "viewPayments" */ './PaymentGateway.vue')
export const Currencies = () => import(/* webpackChunkName: "viewCurrencies" */ './Currencies.vue')
export const AuthManagement = () => import(/* webpackChunkName: "AuthManagement" */'./AuthManagement.vue')
export const AddCreditTransaction = () => import(/* webpackChunkName: "AddCreditTransaction" */'./AddCreditTransaction.vue')
export const AddDebitTransaction = () => import(/* webpackChunkName: "AddDebitTransaction" */'./AddDebitTransaction.vue')

