export const Home = () => import(/* webpackChunkName: "home" */ './Home.vue')
export const Login = () => import(/* webpackChunkName: "login" */ './Login.vue')
export const Register = () => import(/* webpackChunkName: "register" */ './Register.vue')
export const Dashboard = () => import(/* webpackChunkName: "dashboard" */ './App/Dashboard.vue')
export const Settings = () => import(/* webpackChunkName: "Settings" */ './App/Settings.vue')
export const AccountSettings = () => import(/* webpackChunkName: "AccountSettings" */ './App/AccountSettings.vue')
export const WithdrawSettings = () => import(/* webpackChunkName: "WithdrawalSettings" */ './App/WithdrawSettings.vue')
export const Deposit = () => import(/* webpackChunkName: "Deposit" */ './App/Deposit.vue')
export const Invest = () => import(/* webpackChunkName: "Invest" */ './App/Invest.vue')
export const Payouts = () => import(/* webpackChunkName: "Payouts" */ './App/Payouts.vue')
export const WithdrawPage = () => import(/* webpackChunkName: "WithdrawPage" */ './App/WithdrawPage.vue')
export const WalletWithdraw = () => import(/* webpackChunkName: "WalletWithdraw" */ './App/WalletWithdraw.vue')
export const PortFolio = () => import(/* webpackChunkName: "PortFolio" */ './App/Portfolio.vue')
export const BankWithdraw = () => import(/* webpackChunkName: "BankWithdraw" */ './App/BankWithdraw.vue')
export const InvestHistory = () => import(/* webpackChunkName: "InvestHistory" */ './App/InvestHistory.vue')
export const Withdrawals = () => import(/* webpackChunkName: "Withdrawals" */ './App/Withdrawals.vue')
export const HistoryView = () => import(/* webpackChunkName: "HistoryView" */ './App/HistoryView.vue')
export const DepositHistory = () => import(/* webpackChunkName: "DepositHistory" */ './App/DepositHistory.vue')
export const NotFound = () => import(/* webpackChunkName: "NotFound" */ './404.vue')
export const FAQ = () => import(/* webpackChunkName: "FAQ" */ './FAQ.vue')
export const Contact = () => import(/* webpackChunkName: "Contact" */ './Contact.vue')
export const About = () => import(/* webpackChunkName: "About" */ './About.vue')
export const Terms = () => import(/* webpackChunkName: "Terms" */ './Pages/Terms.vue')
export const RegistrationSuccess = () => import(/* webpackChunkName: "RegistrationSuccess" */ './RegistrationSuccess.vue')
export const VerificationStatus = () => import(/* webpackChunkName: "VerificationStatus" */ './VerificationStatus.vue')
export const ValidateWithdraw = () => (/*webpackChunkName: "ValidateWithdraw" */ './App/ValidateWithdraw.vue')

// Pages
export const CrudeOil = () => import(/* webpackChunkName: "CrudeOil" */ './Pages/CrudeOil.vue')
export const IRA = () => import(/* webpackChunkName: "IRA" */ './Pages/Ira.vue')
export const CryptoCurrency = () => import(/* webpackChunkName: "CryptoCurrency" */ './Pages/Cryptocurrency.vue')
export const Commodities = () => import(/* webpackChunkName: "Commodities" */ './Pages/Commodities.vue')
export const Indices = () => import(/* webpackChunkName: "Indices" */ './Pages/Indices.vue')
export const Marijuana = () => import(/* webpackChunkName: "Marijuana" */ './Pages/Marijuana.vue')
export const MetaTrader4 = () => import(/* webpackChunkName: "MetaTrader4" */ './Pages/MetaTrader4.vue')
export const Premium = () => import(/* webpackChunkName: "Premium" */ './Pages/Premium.vue')
export const MetaTrader5 = () => import(/* webpackChunkName: "MetaTrader5" */ './Pages/MetaTrader5.vue')
export const Beginner = () => import(/* webpackChunkName: "Beginner" */ './Pages/Beginner.vue')
export const Intermediate = () => import(/* webpackChunkName: "Intermediate" */ './Pages/Intermediate.vue')
export const Advanced = () => import(/* webpackChunkName: "Advanced" */ './Pages/Advanced.vue')
export const Agriculture = () => import(/* webpackChunkName: "Agriculture" */ './Pages/Agriculture.vue')
export const Forex = () => import(/* webpackChunkName: "Forex" */ './Pages/Forex.vue')

// Auth pages
export const ForgotPassword = () => import(/* webpackChunkName: "ForgotPassword" */ './ForgotPassword.vue')
export const ForgotPasswordSuccess = () => import(/* webpackChunkName: "ForgotPasswordSuccess" */ './ForgotPasswordSuccess.vue')
export const ResetPassword = () => import(/* webpackChunkName: "ResetPassword" */ './ResetPassword.vue')
export const ErrorPage = () => import(/* webpackChunkName: "ErrorPage" */ './ErrorPage.vue')
export const ResetSuccess = () => import(/* webpackChunkName: "ResetSuccess" */ './ResetSuccess.vue')
export const VerificationFailed = () => import(/* webpackChunkName: "VerificationFailed" */ './VerificationFailed.vue')
export const VerificationSuccess = () => import(/* webpackChunkName: "VerificationSuccess" */ './VerificationSuccess.vue')
export const ResendSuccess = () => import(/* webpackChunkName: "ResendSuccess" */ './ResendSuccess.vue')

// AI Features
export { default as AIDashboardView } from './AIDashboardView.vue'
export { default as ConversationHistoryView } from './ConversationHistoryView.vue'
